### ISSUE TITLE
Not working with jetson-stats 4.2.0

### ISSUE THREAD

**Issue by chitoku** [NVIDIA-AI-IOT/ros2_jetson_stats#5]
Hi,

`ros2_jetson_stats` was working with jtop installed on the host up to `jetson-stats` version `4.1.5`, but when the host side jtop upgraded to [`4.2.0`](https://github.com/rbonghi/jetson_stats/releases/tag/4.2.0), it starts showing this error and `ros2_jetson_stats` does not run.

```
[ros2_jtop-3] Traceback (most recent call last):                                                                                                                                
[ros2_jtop-3]   File "/workspaces/isaac_ros-dev/install/ros2_jetson_stats/lib/ros2_jetson_stats/ros2_jtop", line 33, in <module>                                                
[ros2_jtop-3]     sys.exit(load_entry_point('ros2-jetson-stats', 'console_scripts', 'ros2_jtop')())                                                                             
[ros2_jtop-3]   File "/workspaces/isaac_ros-dev/build/ros2_jetson_stats/ros2_jetson_stats/ros2_jtop_node.py", line 165, in main                                                 
[ros2_jtop-3]     rclpy.spin(jtop_publisher)                                                                                                                                    
[ros2_jtop-3]   File "/opt/ros/humble/install/lib/python3.8/site-packages/rclpy/__init__.py", line 222, in spin                                            
[ros2_jtop-3]     executor.spin_once()                                                                  
[ros2_jtop-3]   File "/opt/ros/humble/install/lib/python3.8/site-packages/rclpy/executors.py", line 713, in spin_once                      
[ros2_jtop-3]     raise handler.exception()                                                                                                 
[ros2_jtop-3]   File "/opt/ros/humble/install/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__                            
[ros2_jtop-3]     self._handler.send(None)                                                                                                 
[ros2_jtop-3]   File "/opt/ros/humble/install/lib/python3.8/site-packages/rclpy/executors.py", line 418, in handler                                                             
[ros2_jtop-3]     await call_coroutine(entity, arg)                                                                                                                             
[ros2_jtop-3]   File "/opt/ros/humble/install/lib/python3.8/site-packages/rclpy/executors.py", line 332, in _execute_timer                                                      
[ros2_jtop-3]     await await_or_execute(tmr.callback)                                                                                                                          
[ros2_jtop-3]   File "/opt/ros/humble/install/lib/python3.8/site-packages/rclpy/executors.py", line 107, in await_or_execute                                                    
[ros2_jtop-3]     return callback(*args)                                                                                                                                        
[ros2_jtop-3]   File "/workspaces/isaac_ros-dev/build/ros2_jetson_stats/ros2_jetson_stats/ros2_jtop_node.py", line 136, in jetson_callback
[ros2_jtop-3]     self.arr.status += [gpu_status(self.hardware, self.jetson.gpu[1])]              
[ros2_jtop-3]   File "/home/admin/.local/lib/python3.8/site-packages/jtop/core/common.py", line 68, in __getitem__                                                              
[ros2_jtop-3]     return self._data[key]                                                                                                                                        
[ros2_jtop-3] KeyError: 1                                                                                                                                                       
[ERROR] [ros2_jtop-3]: process has died [pid 6692, exit code 1, cmd '/workspaces/isaac_ros-dev/install/ros2_jetson_stats/lib/ros2_jetson_stats/ros2_jtop --ros-args -r __node:=jtop -r __ns:=/jtop --params-
file /tmp/launch_params_p9kv_w91'].
```

**Comment by rbonghi** [comment]
Hi @chitoku ,

Yes, now, from jetson-stats 4.2.0, the API is changed and requires an update; otherwise doesn't run.
I will fix soon as possible.

**Comment by nakai-omer** [comment]
@rbonghi any updates on this?

**Comment by nakai-omer** [comment]
@rbonghi I have created a PR for supporting latest jetson-stats 4.2.3: https://github.com/NVIDIA-AI-IOT/ros2_jetson_stats/pull/7. Though  it has breaking changes, due to breaking changes in jetson-stats, so not sure on how it should be released.

**Comment by rbonghi** [comment]
Thank you @nakai-omer I merge your PR
