### ISSUE TITLE
Mismatch version jtop service: [4.2.2] and client: [4.2.1]

### ISSUE THREAD

**Issue by nakai-omer** [NVIDIA-AI-IOT/ros2_jetson_stats#6]
Running this packages yields:
```
Jetson Stats has started with interval : 0.5
 You can run following:
  1. $ros2 run rqt_topic rqt_topic 
  2. Services for controlling fan_speed, power_mode, jetson_clocks

Traceback (most recent call last):
  File "/workspaces/isaac_ros-dev/install/ros2_jetson_stats/lib/ros2_jetson_stats/ros2_jtop", line 33, in <module>
    sys.exit(load_entry_point('ros2-jetson-stats', 'console_scripts', 'ros2_jtop')())
  File "/workspaces/isaac_ros-dev/build/ros2_jetson_stats/ros2_jetson_stats/ros2_jtop_node.py", line 163, in main
    jtop_publisher.start()
  File "/workspaces/isaac_ros-dev/build/ros2_jetson_stats/ros2_jetson_stats/ros2_jtop_node.py", line 66, in start
    self.jetson.start()
  File "/usr/local/lib/python3.8/dist-packages/jtop/jtop.py", line 1143, in start
    raise JtopException("""Mismatch version jtop service: [{service_version}] and client: [{client_version}]. Please run:\n
jtop.core.exceptions.JtopException: Mismatch version jtop service: [4.2.2] and client: [4.2.1]. Please run:
sudo systemctl restart jtop.service
```

Running `sudo systemctl restart jtop.service` doesn't help

**Comment by nakai-omer** [comment]
Ok found that is because of the jetson-stats python version which is 4.2.1 in the isaac_ros_common docker container
